"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MLJszWTM01G
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useRef, useState } from "react";

export function ReleaseNotes({
  onSubmit,
  notes,
}: {
  onSubmit: (startDate: string, endDate: string) => void;
  notes?: string;
}) {
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  return (
    <div className="bg-gray-50 dark:bg-gray-950 py-12 w-full">
      <div className="w-full mx-auto px-4">
        <div className="space-y-4">
          <h1 className="text-3xl font-bold tracking-tight">
            Release Notes Generator
          </h1>
          <div className="space-y-2">
            <div className="grid gap-2">
              <div className="flex items-center gap-2">
                <Label htmlFor="start-date">Start Date</Label>
                <Input
                  id="start-date"
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                />
              </div>
              <div className="flex items-center gap-2">
                <Label htmlFor="end-date">End Date</Label>
                <Input
                  id="end-date"
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                />
              </div>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="release-notes">
                Release Notes
                <span className="text-sm font-normal">
                  (in markdown format)
                </span>
              </Label>
              <div
                className="min-h-[500px] resize-none whitespace-pre-wrap"
                id="release-notes"
              >
                {notes || "No release notes generated yet."}
              </div>
            </div>
            <Button
              variant="outline"
              onClick={(e) => {
                e.preventDefault();
                onSubmit(startDate, endDate);
              }}
              disabled={!startDate || !endDate}
            >
              Generate
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
