"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MLJszWTM01G
 */
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { useMemo, useRef } from "react";

export function ReleaseNotes({
  onSubmit,
  notes,
}: {
  onSubmit: (startDate: string, endDate: string) => void;
  notes?: string;
}) {
  const lastSeveralMondays = useMemo(() => {
    const today = new Date();
    const day = today.getDay();
    const diff = today.getDate() - day + (day === 0 ? -6 : 1); // adjust when day is sunday
    const lastMonday = new Date(today.setDate(diff));
    const mondays = [];
    for (let i = 0; i < 10; i++) {
      mondays.push(new Date(lastMonday.setDate(lastMonday.getDate() - 7)));
    }
    return mondays;
  }, []);
  const dateRef = useRef<HTMLSelectElement>(null);
  return (
    <div className="bg-gray-50 dark:bg-gray-950 py-12 w-full">
      <div className="w-full mx-auto px-4">
        <div className="space-y-4">
          <h1 className="text-3xl font-bold tracking-tight">
            Release Notes Generator
          </h1>
          <div className="space-y-2">
            <div className="grid gap-2">
              <div className="flex items-center gap-2">
                <Label htmlFor="start-date">Start Date</Label>
                <select className="bg-gray-50 dark:bg-gray-950" ref={dateRef}>
                  {lastSeveralMondays.map((date) => (
                    <option key={date.toISOString()} value={date.toISOString()}>
                      {date.toDateString()}
                    </option>
                  ))}
                </select>
              </div>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="release-notes">
                Release Notes
                <span className="text-sm font-normal">
                  {" "}
                  (in markdown format)
                </span>
              </Label>
              <div
                className="min-h-[500px] resize-none whitespace-pre-wrap font-mono text-sm mt-4"
                id="release-notes"
              >
                {notes || "No release notes generated yet."}
              </div>
            </div>
            <Button
              variant="outline"
              onClick={(e) => {
                e.preventDefault();
                const startDate = dateRef.current?.value;
                if (!startDate) return;
                onSubmit(
                  startDate,
                  // to the following sunday
                  new Date(
                    new Date(startDate).setDate(
                      new Date(startDate).getDate() + 6
                    )
                  ).toISOString()
                );
              }}
            >
              Generate
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
